name: flutter_score_slider
description: Simple & customizable Flutter slider widget for score selections.
version: 2.0.0
homepage: https://github.com/Applitom/flutter_score_slider

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
